path:
train: images/train
val: images/validation
test: images/test

# Classes (donde se identifica los distintos tipos de objetos)
names:
  0: white-rook
  1: black-bishop
  2: black-king
  3: black-knight
  4: black-pawn
  5: black-queen
  6: black-rook
  7: white-bishop
  8: white-king
  9: white-knight
  10: white-pawn
  11: white-queen
  12: chess-pieces

#   'chess-pieces', 'bishop', 'black-bishop', 'black-king', 'black-knight', 'black-pawn', 'black-queen', 'black-rook', 'white-bishop', 
# 'white-king', 'white-knight', 'white-pawn', 'white-queen', 'white-rook'